repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: golangci-lint
        args: ["--timeout", "180s"]
  - repo: local
    hooks:
      - id: run-make-backend-docs
        name: Make backend docs
        entry: make backend_docs
        language: system
