services:
  app:
    profiles: [app]
    image: cloud-paas:latest
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file: .env
    environment:
      - DB_URL=host=db user=paas password=paas dbname=paas
    networks:
      - paas

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: paas
      POSTGRES_PASSWORD: paas
      POSTGRES_DB: paas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - paas

networks:
  paas:

volumes:
  postgres_data: