services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: paas
      POSTGRES_PASSWORD: paas
      POSTGRES_DB: paas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-config.json
    ports:
      - 7079:8080
    volumes:
      - ./dist/keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json
      - keycloak-data:/opt/keycloak/data

    command: ["start-dev", "--import-realm"]
    restart: unless-stopped

volumes:
  postgres_data:
  keycloak-data: