apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.deploymentName }}'
  namespace: '{{ .Values.namespace }}'
type: Opaque
stringData:
  {{- range $key, $value := default dict .Values.envVariables }}
    {{ $key }}: {{ $value }}
  {{- end }}
