apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.deploymentName }}'
  namespace: '{{ .Values.namespace }}'
spec:
  selector:
    app.kubernetes.io/name: '{{ .Values.deploymentName }}' 
  ports:
    - protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
