apiVersion: v1
kind: Secret
metadata:
  name: paas-secrets
type: Opaque
data:
  db_password: {{ .Values.db.password | b64enc }}

  registry_repo_uri: {{ .Values.registry.repo_uri | b64enc }}
  registry_user: {{ .Values.app.registry.user | b64enc }}
  registry_password: {{ .Values.app.registry.password | b64enc }}
