apiVersion: v1
kind: Secret
metadata:
  name: paas-secrets
type: Opaque
data:
  postgres_password: {{ .Values.app.postgres_password | b64enc }}
  registry_repo_uri: {{ .Values.app.registry_repo_uri | b64enc }}
  registry_user: {{ .Values.app.registry_user | b64enc }}
  registry_password: {{ .Values.app.registry_password | b64enc }}