apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.fullname" $ }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "deployment.labels" . | nindent 8 }}