docker:
  enabled: true
  image: "docker:28.0.4-dind"
  replicas: 1
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"

replicaCount: 1

image:
  repository: ghcr.io/thomasrubini/cloud-paas
  pullPolicy: Always

serviceAccount:
  name: "paas"

service:
  type: ClusterIP
  port: 8080

# FIXME
volumes:
  - name: paas-data
    persistentVolumeClaim:
      claimName: paas-data

volumeMounts:
  - name: paas-data
    mountPath: /paas-data

db:
  password: &db_password "paas"
  url: "host=paas-postgresql user=paas dbname=paas" #FIXME

app:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  repo_fetch:
    enable: true
    period_secs: 120
  repo_dir: "/paas-data/repos"
  secrets:
    impl: "file"
    impl_file: "/paas-data/secrets.json"
  registry:
    repo_uri: "paas-docker-registry.paas.svc.cluster.local:30005/library"
    user: ""
    password: ""
    tag_prefix: paas
  kube:
    deployment_prefix: paas

postgresql:
  enabled: true
  auth:
    username: paas
    password: *db_password
    database: paas
  primary:
    persistence:
      enabled: true
      size: 8Gi

docker-registry:
  service:
    type: NodePort
    port: 30005
    nodePort: 30005
  podLabels:
   "paas/resource": "docker-registry"
