ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: paas.phoenix.dopolytech.fr
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: paas-tls
     hosts:
       - paas.phoenix.dopolytech.fr

image:
  tag: "latest" # Override the versionning of the chart

app:
  oidc:
    base_url: "http://localhost:7079"
    user_id: "paas-backend"
    user_password: "paas-backend"
    realm: "master"
    client_id: "paas-backend"
    client_secret: "paas-backend"
  registry:
    repo_uri: "harbor.phoenix.dopolytech.fr/library"
    user: "admin"
    password: "CHANGE_ME"
