ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: paas-tls
     hosts:
       - example.com

image:
  tag: "latest" # Override the versionning of the chart

app:
  verbose: "0"
  oidc:
    base_url: "http://localhost:7079"
    user_id: "paas-backend"
    user_password: "paas-backend"
    realm: "master"
    client_id: "paas-backend"
    client_secret: "paas-backend"
