ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: localhost # change with your website domain name
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: paas-tls
     hosts:
       - localhost # change with your website domain name

image:
  tag: "latest" # Override the versionning of the chart

app:
  verbose: "0"
